name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - xeus-python
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - pandas
  - seaborn
  - jupyterlab-miami-nights